don't push anything dangerous

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -53,11 +53,6 @@ jobs:
           echo "PRE_MERGE_COMMIT=$pre_merge" >> $GITHUB_ENV
           git checkout -b "publish.yml/pr-${PULL_REQUEST}" "$merge_commit"
 
-          git checkout main -- .github
-          if ! git diff --quiet; then
-            git add .github/**
-            git commit -m 'Update .github directory to match main branch'
-          fi
         env:
           PULL_REQUEST: ${{ github.event.inputs.pull_request }}
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -73,6 +68,11 @@ jobs:
             --branch-okay "$PULL_REQUEST" \
             --no-cherry-pick \
             --clean
+          # abort if .github was modified since $PRE_MERGE_COMMIT
+          if ! git diff --quiet "$PRE_MERGE_COMMIT" -- .github; then
+            echo ".github/ was modified; aborting"
+            exit 1
+          fi
 
       - name: Push commits
         uses: Homebrew/actions/git-try-push@main
